package pl.mathrill.roas.model;

public enum ShippingType {
	ODBIOR_PACZKI_BLAD,
	ODBIOR_PACZKI_REKLAMACJA,
	REKLAMACJA,
	REKLAMACJA_ALLEGRO,
	WYSYLKA_PRYWATNA,
	WYSYLKA_BRAKU_PAKOWANIE,
	WYSYLKA_BRAKU_WYPISANIE,
	WYMIANA_TOWARU_PAKOWANIE,
	WYMIANA_TOWARU_WYPISANIE,
	WYMIANA_TOWARU_NA_RZYCZENIE,	
}
